### ISSUE TITLE
Crashing PilotsDeck.exe causes MSFS CTD

### ISSUE THREAD

**Issue by EisernUnion** [Fragtality/PilotsDeck_FNX#12] opened 2023-02-09 11:55 UTC
Hi, 
sometimes MSFS freeze, sound stops and CTD... 99% happend instantly after PilotsDeck.exe crash

![image](https://user-images.githubusercontent.com/42810795/217806094-860fe741-5c97-4b70-b11a-7128e38ed287.png)

**Comment by Fragtality** [comment] 2023-02-09 12:32
So your definition of instant is 49 Minutes? :open_mouth:

Even when I put aside the time discrepancy, I do not see anything I could do about it. Or even a theoretical Cause how the Plugin could cause a CTD of the Simulator. It does only interact indirectly with the Sim through FSUIPC and the C# Client.
Also I see that the Exception (of the Plugin) was caused because the connection was closed by the remote party.

Are there any Steps to reproduce the Situation?
Does this also happen with the current Dev-Build? 

On top of that, your Issue is in the wrong Repo.

**Comment by EisernUnion** [comment] 2023-02-09 12:54
oh... you are right ^^ its not quite instant... but those 3 are always in combination ... maybe just a coincidence....  hmm maybe was to fast to open an issue :) awkward ..^^

**Closed** 2023-02-10 22:04 UTC
