### ISSUE TITLE
Rudder Trim display

### ISSUE THREAD

**Issue by Delta-Charlie-DEV** [Fragtality/PilotsDeck_FNX#8] opened 2023-01-13 10:50 UTC
Hi !

I noticed that the rudderStr offset returns the value of the TRIM + rudder pedals . 
So, the value is correct if the pedals are neutral, but give a wrong information as soon as you move the pedals ...
Is there anyway to only set the trim value (as intended) ?

**Comment by Fragtality** [comment] 2023-01-13 11:12
Oh damn - you're right.
I'll have look at that.

**Comment by Delta-Charlie-DEV** [comment] 2023-01-13 11:31
Also, it seems the string is to small  (6 chars), if the trim is greater than 10 then you loose the decimal value.
Well, I've never flied with a rudder trim > 10, but, who knows ... :-)

**Comment by Fragtality** [comment] 2023-01-13 19:45
Try that: https://github.com/Fragtality/PilotsDeck_FNX/raw/master/PilotsDeck_FNX2PLD-latest.zip

Did not have the Time yet to test it thoroughly, but the Rudder Display should now display only the Trim 😉 

And yeah, I really overlooked such great Trim-Values, good Catch! 😅 
I have added a "quick-fix": Instead of making the String longer, I just leave out the Space now when the Values get that high. Does not brake anybody's Integration but still shows the full Value now! 😃

**Comment by Fragtality** [comment] 2023-01-13 19:51
And also: you seem to develop an Integration for Sim Innovations Air Manager based on my Tool, right?

Maybe check out the Raw-Value Mode: it exports all Data as Numeric Values to Offsets instead of formatted Strings. If that is easier for your Logic to handle, you can use that. This Feature was specifically added to support other 3rd Party Software/Hardware!

**Comment by Delta-Charlie-DEV** [comment] 2023-01-16 06:39
Hi,
I tried the latest build but the offset ( <rudderStr> is at Address 0x5449:s:6 ) seems to stay at 0.
The raw mode is a good value, but now I've set up everything based on strings, so ... :-)
I quickly tried to see what is gives, but it's a pain in FSUIPC to find the type for each variable :-)

**Comment by Fragtality** [comment] 2023-01-16 12:54
Is it always 0, even in different Fenix-/Sim-Sessions? 

Please fetch the latest again. Maybe you fetched an early copy which hadn't the 3 Locations I found. I've added also some Debug-Information to the Logs. So if it happens again, please send me the Log.

> The raw mode is a good idea, but now I've set up everything based on strings, so ... :-)
I quickly tried to see what is gives, but it's a pain in FSUIPC to find the type for each variable :-)

Just so that you know that there would be an Alternative 😉 
But what exactly do you mean with the pain of finding the type in FSUIPC? Could something be improved in the Log-Message to make it easier?

**Comment by Fragtality** [comment] 2023-01-16 19:23
Please redownload it:
https://github.com/Fragtality/PilotsDeck_FNX/raw/master/PilotsDeck_FNX2PLD-latest.zip

Could not reproduce it, but had an Idea what might be the Issue

**Comment by Fragtality** [comment] 2023-01-17 23:21
I need Feedback, I would like to close this as fixed 😉

**Comment by Delta-Charlie-DEV** [comment] 2023-01-18 10:11
Hi ! You may close as fixed, that's perfect !

**Comment by Fragtality** [comment] 2023-01-18 13:07
So the Rudder Display now works reliably?

**Comment by Delta-Charlie-DEV** [comment] 2023-01-18 13:39
Yes, sorry I didn't mention it.

![image](https://user-images.githubusercontent.com/76492436/213185951-afde1cd6-c9c0-4e45-a87a-0976972016f5.png)
![image](https://user-images.githubusercontent.com/76492436/213186085-4b4fcf23-73b2-4f65-92ab-fb58ae3d7aca.png)

**Comment by Fragtality** [comment] 2023-01-18 13:53
Nice ! 😄 

Then I can package it with the next Profile/Integration ^^

**Closed** 2023-01-18 13:54 UTC
Labels: bug
