### ISSUE TITLE
Changing  Air Speed and VS while they are in managed mode

### ISSUE THREAD

**Issue by Samhaho** [Fragtality/PilotsDeck_FNX#1] opened 2022-10-18 09:37 UTC
In the Fenix when speed is managed you can turn the encoder to increase  or decrease the speed. While doing so the speed is still managed and the dot is displayed however the speed changes is also displayed (dashes are replaced by the speed being set by the encoder).  This allows to select the target speed before pulling to switch from managed to selected speed mode. With the Pilots_Deck app the behavior is different: When  the speed is managed and you turn the encoder the offset that displays the speed shows dashes so you cannot visualize the speed changes to select the new target speed.  So to set a  selected speed you need to pull (switch to selected speed) before turning the encoder to set the new target speed, which is not ideal. The same holds for VS.

**Comment by Fragtality** [comment] 2022-10-18 21:09
That is because there is no way (I could know of) to get the Information when a Display is "dashed" reliably. I would have done better if possible ;) 
Like described: the Binary is a Memory-Hack. It is a "best effort solution" to get at least some Information out of the Fenix because there is no real SDK / API currently available and unlikely if there ever will be.

Other Busses do expose that "Is Dashed" Information (FBW, FSL, ToLiSS).

**Comment by Samhaho** [comment] 2022-10-18 21:48
First, many thanks for  this breakthrough. It is a major progress. I understand very well that this is a hack because Fenix (unlike all other add-on) does not  expose outputs. Planty of people (home cockpit amateur have been waiting for this. It is just strange that you can get the dash and the dot info almost all reliable except in this case. Wouldn't it be other spot in memory that expose the value of speed while the offset shows the wrong dash? Actually this value  replaces the "wrong" dash as soon as  you switch to selected mode. So it must be stored some where.. (just wondering).  Thanks again for the great job.

**Comment by Fragtality** [comment] 2022-10-19 18:46
> It is just strange that you can get the dash and the dot info almost all reliable except in this case

That has to be differentiated: the "dot information" is very reliable - it is exposed by Fenix in the "I_FCU_XXX_MANAGED" LVars. the "dashed information" is not exposed and I did not found it (either directly or indirectly). 
So I can only guess respectively go for the least confusing way. Airspeed for example only shows a value when in selected Mode. A preselected Speed in Managed Mode is not show - when Managed Mode is on, the Display is set "---*". Because I can't reliably determine if a value is currently shown and when it is cleared again.

> Wouldn't it be other spot in memory that expose the value of speed while the offset shows the wrong dash? Actually this value replaces the "wrong" dash as soon as you switch to selected mode.

Not sure if I could follow you here. And I don't know how far you understand the principles behind that.
The Memory Locations change every time with every Fenix/Sim Session. During Development, I have to identify Byte-Patterns which always (or almost always) stay the same with a persistent Offset to the Location for given Value.
When the Binary is used, it searches for these Byte-Patterns in the Fenix Exectuables, applies the Offset to that Location and that yields the current Memory-Location for any Value.
When I search for the Values (during Development), the FCU Values are rather easy. I can search for the Number I see in the Display. Change it and rescan for the new Number. And therefore can cleary identify what the Location is (then I search for suitable Byte-Pattern and Offset to find it with every new Session).
But a Information like "isDashed" is likely a Boolean. So somewhere a bit is flipping. And even when the Plane is sitting on the Ground with GPU Power, there are so many memory Changes that I can't really identify within Gigs of Memory which of these flipping Bits was the change on the FCU Display. 

> So it must be stored some where.. (just wondering).

It surely is somewhere! If I should someday find it, rest assured I'll add it to the Binary ;D

**Comment by Samhaho** [comment] 2022-10-19 19:48
I very much appreciate you're taking the time to explain and clarify.  Although the pattern search principle was clear in my mind (only the general principle though) my confusion came from my assumption that what you store in the offset come directly as is from Fenix. For example when the offset  displays airspeed ---*  I assumed that this is a direct copy of of Fenix memory airspeed content (including the string type). The same for  heading/VS vs TRK/FPA for example. This is why I found it strange that the info was not correct in the case of managed airspeed when turning the encoder. I understand now that this was a wrong assumption. The content of the offset is a combination of relavant data that you are able to find thanks to your pattern search algorithm + some other  data coming from exposed Lvars (such "I_FCU_XXX_MANAGED")+ some other logic that you use  (for example when to dash or not) to "guess" data that do not have.

Me first and lot of people around me (in the Mobiflight discord) are very happy with what we have already. So thanks a lot for your effort and for sharing.

**Comment by Fragtality** [comment] 2022-10-20 08:08
> Me first and lot of people around me (in the Mobiflight discord) are very happy with what we have already. So thanks a lot for your effort and for sharing.

You're all welcome :)
For the Binary to be more usable, I maybe could build a different mode how the Data is written to FSUIPC Offsets. So instead of writing finished String, the Binary could write the numeric/boolean Values to Offsets? So that Users with different Hardware/Use-Case (Mobi, Spad, other than PilotsDeck) have more control of what is shown.
Would that be something?

**Comment by Samhaho** [comment] 2022-10-20 10:55
That would be a good idea. Many thanks

**Comment by bennnozgurumm** [comment] 2022-10-21 14:43
Hi Fragtality, first of all we thank you for this great work for Fenix. That was what we are waiting for our FCUs... :) Although I am not flying with Fenix. I have simulated 90% with your .exe. I read the messages about Samhaho's issue which is about Preselected mode of SPD. Actually the only things are the values of the SPD display "XXX". With mobiflight we can manage to make it work when we get the SPD values. I see you have done all the values in strings. Yes it is very easy to adjust  the mobiflight in this way. However, we can do it when we get the values in "int" or "byte(s)" format. 

You can't believe how I get the "isTRKmode on" value :) when it is FPA your string max 4 digit but in VS it is 5 digit. I tell the mobiflight look at the digit 4 and if it is " " (space) it is FPA otherwise it is VS. :) 

Finally if you give us the values in bytes even it is managed mode, (because in Fenix, the numbers are changing and I think your program can discover and get it) we can program the rest in MF...

Thank you very much again!

**Comment by Fragtality** [comment] 2022-10-21 19:10
> I see you have done all the values in strings. Yes it is very easy to adjust the mobiflight in this way. However, we can do it when we get the values in "int" or "byte(s)" format.

Yeah it was primarly developed to support my PilotsDeck Profile. Normally, with other Planes, I go ahead and write a Lua Script (run by FSUIPC) which takes the different FCU Values and States and builds a String to display on the StreamDeck. With the Fenix that "formatting logic" is in the Binary.
A byte, word or integer is surely possible. But written to where? ;) To FSUIPC Offsets? To custom Lvars?

> You can't believe how I get the "isTRKmode on" value :) when it is FPA your string max 4 digit but in VS it is 5 digit. I tell the mobiflight look at the digit 4 and if it is " " (space) it is FPA otherwise it is VS. :)

why that way?!^^
That Information is directly exposed by Fenix in the Lvar I_FCU_TRACK_FPA_MODE  ;)
see https://github.com/Fragtality/PilotsDeck_FNX/blob/master/PilotsDeck_FNX2PLD/ElementManager.cs#L155

> Finally if you give us the values in bytes even it is managed mode, (because in Fenix, the numbers are changing and I think your program can discover and get it) we can program the rest in MF...

Yeah sure, that would be roughly the Idea. I expose the Values directly, so that you folks can go ahead and use these Values the way it is needed . Or put differently: to put you in the same Situation what I do normally with a Lua Script (like described above) :)

**Comment by Fragtality** [comment] 2022-12-06 17:08
@Samhaho 
@bennnozgurumm 

I've added a new "Raw Value Mode" which writes the numeric Values to FSUIPC Offsets (as direct as possible). An Example from the Log:
```
FSUIPC Offset <fcuSpd> is at Address 0x5408 (Type: float, Size: 4)
FSUIPC Offset <fcuHdg> is at Address 0x540C (Type: int, Size: 4)
FSUIPC Offset <fcuAlt> is at Address 0x5410 (Type: int, Size: 4)
FSUIPC Offset <fcuVs> is at Address 0x5414 (Type: float, Size: 4)
FSUIPC Offset <isisStd> is at Address 0x5418 (Type: byte, Size: 1)
FSUIPC Offset <isisBaro> is at Address 0x5419 (Type: float, Size: 4)
FSUIPC Offset <comActive> is at Address 0x541D (Type: int, Size: 4)
FSUIPC Offset <comStandby> is at Address 0x5421 (Type: int, Size: 4)
FSUIPC Offset <xpdr> is at Address 0x5425 (Type: short, Size: 2)
FSUIPC Offset <bat1> is at Address 0x5427 (Type: float, Size: 4)
FSUIPC Offset <bat2> is at Address 0x542B (Type: float, Size: 4)
FSUIPC Offset <rudder> is at Address 0x542F (Type: float, Size: 4)
```
Is that what you guys needed?
If yes, I could push that Code and make a Release for you to play with ;)

**Comment by Samhaho** [comment] 2022-12-06 18:47
Great. It is good idea to have both formats.

 

This is unrelated, but I am having two issues (not majors one though)

1.	For me PilotsDeck_FNX is not able to detect Fenix when I switch from another aircraft to Fenix without restarting MSFS. Is that a known issue or this is just me?
2.	I am running PilotsDeck_FNX from FSUIPC.ini. Sometimes I do not get any output from FSUIPC (nothing is read) despite that the log seems to show that PilotsDeck_FNX has detected Fenix and it is retrieving the data and feeding them to FSUIPC. How to troubleshoot this situation?

 

Many thanks for your wonderful effort.

 

Sam

**Comment by bennnozgurumm** [comment] 2022-12-06 19:45
Thank you very much my friend... Thx for your great effort of course that
values will be better to play with and manage some situations. :) 🙏🙏🙏

6 Ara 2022 Sal 21:47 tarihinde Samhaho ***@***.***> şunu
yazdı:

**Comment by Fragtality** [comment] 2022-12-06 20:47
Version 0.6 ready to download [here](https://github.com/Fragtality/PilotsDeck_FNX/releases/tag/v0.6).
Mind the .NET 7 Requirement and that the "Raw Mode" is not enabled by default! (Set "rawValues" to "true" in PilotsDeck_FNX2PLD.dll.config)
<br/>

> 1. For me PilotsDeck_FNX is not able to detect Fenix when I switch from another aircraft to Fenix without restarting MSFS. Is that a known issue or this is just me?

That is a known Issue with MSFS / FSUIPC.
MSFS reports every Lvar that existed in that Session and FSUIPC (WASM-Module) has a Limit of 3066 LVars for Transmission. So when you load (or even start the Sim with) a complex Airliner like the A310 for example, the limit is already reached. When you then load the Fenix (same Sim Session), the WASM Module of FSUIPC can't transmit the Fenix Lvars. Then nothing works which needs to access these Lvars (not even FSUIPC itself, i.e. in Lua-Scripts).
So thanks to Asobo, the old FSX/P3D one-plane-per-simulator-session Rule continues to exist. It is even worse now: you have to set the next Plane when you exit the previous Session.
See in the [FSUIPC-Forums](https://forum.simflight.com/topic/97132-missing-lvar-after-3066-lvars-loaded-since-su11/).
<br/>


> 2. I am running PilotsDeck_FNX from FSUIPC.ini. Sometimes I do not get any output from FSUIPC (nothing is read) despite that the log seems to show that PilotsDeck_FNX has detected Fenix and it is retrieving the data and feeding them to FSUIPC. How to troubleshoot this situation?

Sounds related to Problem 1! The "normal mode" which you are used to, only started to write strings when one of two Lvars has a Value of 1. But because of the Situation described above, no Lvar-read works (the Values stay 0). So your read to the Offset might be working, but it has nothing been written there by the Binary you could read (only an empty string).

It also could be Problem with the Library Versions. If that was the Cause, it should be gone now.

**Comment by demariners** [comment] 2022-12-06 23:21
Hey there!  Love this.  Anyway, downloaded latest version and notice SPD no longer works.  Not sure why.

**Comment by Fragtality** [comment] 2022-12-07 01:21
And I have no Clue why Speed does not work :/
The Location in Memory has not changed and never saw an alternative Location (like with other Variables). The Logic how the Values for FSUIPC are generated also has not changed (for the "normal" mode / formatted string output).

How / With what are you using this Binary? With my PilotsDeck Plugin and the premade Profiles? Or with some other 3rd Party Software like MobiFlight?

How / when is the Binary started?

Is that also the case if MSFS is directly started with the Fenix?

**Comment by demariners** [comment] 2022-12-07 01:22
I just loaded your .exe.  I use Spad.next which reads from FSUIPC.  I can see everything else just fine.

**Comment by Fragtality** [comment] 2022-12-07 01:48
Hmm maybe Spad was just not correctly configured for that Offset?
0x5408:s:10 Means that it is of type string with Length of (up-to) 10.

**Comment by Samhaho** [comment] 2022-12-07 09:43
Many thanks for your reply regarding the issues. This is very helpful.

 

Sorry for this but I couldn’t find the .exe file in version 0.6, am I missing something?

 

Sam

**Comment by Fragtality** [comment] 2022-12-07 19:49
*DOH* !! I completely forgot to attach the Archive with the Binary xD
Now corrected :)

**Comment by Fragtality** [comment] 2022-12-09 10:12
Closing this Issue - Enhancement/Feature seems to be implemented as wished ;)

**Closed by Fragtality** 2022-12-09 10:12 UTC
Labels: enhancement
